name: Simple Configuration
description: 'Simplified configuration page that is more usable to Site Managers.'
type: module
core_version_requirement: ^8 || ^9 || ^10
package: SiteFarm
configure: sitefarm.admin_index
